import Link from "next/link";
import Image from "next/image";
import { requireAdmin } from "@/lib/auth";
import { getAdmin } from "@/lib/firebase-admin";
import { getHeroSettings } from "@/lib/firestore";
import { Arrow, Plus } from "@/components/ui/icons";

export default async function Dashboard() {
  await requireAdmin();
  const collection = getAdmin().db.collection("products");
  const [total, active, discounted, hero] = await Promise.all([collection.count().get(), collection.where("active", "==", true).count().get(), collection.where("hasDiscount", "==", true).count().get(), getHeroSettings()]);
  return <><div className="admin-page-heading"><div><span className="eyebrow">YOUR BRAND, AT A GLANCE</span><h1>Welcome to your studio.</h1><p>A little care behind every unforgettable impression.</p></div><Link href="/admin/products/new" className="button button-dark"><Plus />Add product</Link></div><div className="dashboard-stats">{[{ label: "Total products", value: total.data().count, detail: "In your collection" }, { label: "Active products", value: active.data().count, detail: "Visible on your website" }, { label: "Discounted products", value: discounted.data().count, detail: "With a current offer" }].map((stat, index) => <div className="stat" key={stat.label}><div><span>{stat.label}</span><span className="stat-index">0{index + 1}</span></div><strong>{String(stat.value).padStart(2,"0")}</strong><small>{stat.detail}</small></div>)}</div><div className="dashboard-grid"><section className="admin-panel dashboard-hero"><div className="panel-heading"><h2>Your first impression</h2><Link href="/admin/hero" className="text-link">Edit hero <Arrow diagonal width={15} height={15} /></Link></div><div className="dashboard-hero-image"><Image src={hero.poster.url} alt={hero.poster.alt} fill sizes="(max-width: 900px) 90vw, 50vw" className="object-cover" /><div><span className="eyebrow">{hero.enabled && hero.video ? "CAMPAIGN FILM ENABLED" : "POSTER DISPLAY"}</span><h3 className="preserve-lines">{hero.heading}</h3></div></div><p className="field-hint">{hero.video?.name || "No desktop video uploaded"}</p></section><section className="admin-panel quick-actions"><h2>Make it yours</h2><p className="panel-description">A few thoughtful updates can make all the difference.</p>{[{ href: "/admin/products/new", title: "Introduce a fragrance", description: "Add a new product to your collection" }, { href: "/admin/hero", title: "Set the scene", description: "Update your campaign film and headline" }, { href: "/admin/settings", title: "Start a conversation", description: "Manage WhatsApp and your brand story" }, { href: "/admin/media", title: "Keep things considered", description: "Review uploaded media and unused files" }].map(action => <Link key={action.href} href={action.href}><span><strong>{action.title}</strong><small>{action.description}</small></span><Arrow diagonal /></Link>)}</section></div></>;
}
